#
# Copyright (c) 2024 General Motors GTO LLC.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-FileType: DOCUMENTATION
# SPDX-FileCopyrightText: 2023 General Motors GTO LLC
# SPDX-License-Identifier: Apache-2.0
#
[versions]
android = "8.2.1"
androidx-appcompat = "1.4.2"
androidx-espresso = "3.5.1"
androidx-junit = "1.1.5"
junit = "4.13.2"
mockito = "4.6.1"
robolectric = "4.7.3"
up-java = "1.5.6"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso"}
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit"}
junit = { module = "junit:junit", version.ref = "junit"}
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito"}
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito"}
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito"}
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric"}
up-java = { module = "org.eclipse.uprotocol:up-java", version.ref = "up-java" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
